name: Weekly Retrain

on:
  schedule:
    - cron: "0 3 * * 1"   # Every Monday at 03:00 UTC
  workflow_dispatch:       # Allow manual retraining too

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Call retrain endpoint
        run: |
          # Call the retrain API and save response
          curl -sS "https://forecast-service-q7u9.onrender.com/forecast?metric1=interviews&metric2=cvssent&metric3=companiesadded&datefrom=2025-01-01&dateto=2025-12-31&output=weekly&horizon=8&train=true" \
          -o retrain_result.json

      - name: Show retrain result
        run: cat retrain_result.json

      - name: Save retrain result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: retrain-logs
          path: retrain_result.json
